title: "Rust学習日記"
summary: |-
  最近流行っているRustを学びたいと思い、学習日記をつけていこうと思い立った次第でございます。
  
  ■本日記の位置づけ
  ・備忘録
  ・学習記録の軌跡を参考にしてもらう
  ・詰まったところを共有したい
  
  位置づけとしてはこんな感じです。
  
  因みに、対象読者は一つ以上の言語を業務で使っているような方、もしくは学習を済ませた方です。
  全くプログラミングが初めてという方は対象読者として想定しておりませんので悪しからず・・・。
  なので、if文の説明等プログラミングの根本的なことはお話せずにサクサクと進めていきます。
  
  ※本書においては「Rust言語」のことを「Rust」と呼称していきます。
  ※錆の話をしているのではありません。

topics: ["rust", "初心者", "学習日記"]
published: true
price: 0
toc_depth: 2
allow_override: true
chapters:
  - 00_hello-world
  - 01_fizzbuzz
  - 02_types-variable
